- full_name: "Vishal Kapadia"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"

- full_name: "Myra H Wyckoff"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"

- full_name: "Eric B Ortigoza"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"

- full_name: "Rachel L Leon"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"

- full_name: "Venkatakrishna Kakkilaya"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"

- full_name: "Abhishek Makkar"
  affiliations:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"