- name: "Kapadia V"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"

- name: "Wyckoff M"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"

- name: "Ortigoza E"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"

- name: "Leon R"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"

- name: "Kakkilaya V"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"

- name: "Makkar A"
  affiliation_keywords:
    - "UT Southwestern"
    - "UTSW"
    - "University of Texas Southwestern"
    - "University of Texas Southwestern Medical Center"
    - "The University of Texas Southwestern Medical Center"
